services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mylearningdb?sslmode=disable
      - JWT_SECRET=938133c4134970591abfeae8cc35c543c5da49dfa269baa0c68f6ea66796205d
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mylearningdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "mylearningdb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: